2019-09-24 19:31:12,419|13348|INFO|||log_trace.py|inner|57|||||||||开始执行aa模块
2019-09-24 19:31:12,609|13348|INFO|||log_trace.py|inner|59|||||||||开始执行aa中车辆查询2的用例
2019-09-24 19:31:12,610|13348|INFO|||testTrucks.py|aa|21|||||||||运行aa方法
2019-09-24 19:31:12,610|13348|INFO|||log_trace.py|inner|67|||||||||结束执行aa中车辆查询2的用例
2019-09-24 19:31:12,611|13348|INFO|||log_trace.py|inner|68|||||||||结束执行aa模块
2019-09-24 19:38:21,695|8104|INFO|||log_trace.py|inner|38|||||||||开始执行aa中车辆查询2的用例
2019-09-24 19:38:21,696|8104|INFO|||log_trace.py|inner|42|||||||||执行aa中车辆查询2的用例出错啦
2019-09-24 19:38:39,749|6052|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 19:38:39,751|6052|INFO|||log_trace.py|inner|46|||||||||结束执行test_get_trucks中车辆查询2的用例
2019-09-24 19:41:23,303|10704|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 19:41:23,304|10704|INFO|||log_trace.py|inner|42|||||||||执行test_get_trucks中车辆查询2的用例出错啦
2019-09-24 19:43:36,671|5724|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 19:43:36,672|5724|INFO|||log_trace.py|inner|42|||||||||执行test_get_trucks中车辆查询2的用例出错啦
2019-09-24 20:10:48,015|9816|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 20:10:48,016|9816|INFO|||log_trace.py|inner|42|||||||||执行test_get_trucks中车辆查询2的用例出错啦
2019-09-24 20:17:31,153|264|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 20:17:31,153|264|INFO|||log_trace.py|inner|42|||||||||执行test_get_trucks中车辆查询2的用例出错啦
2019-09-24 20:17:31,154|264|INFO|||log_trace.py|inner|47|||||||||结束执行test_get_trucks模块
2019-09-24 20:18:00,420|13428|INFO|||log_trace.py|inner|38|||||||||开始执行test_get_trucks中车辆查询2的用例
2019-09-24 20:18:00,421|13428|INFO|||log_trace.py|inner|46|||||||||结束执行test_get_trucks中车辆查询2的用例
2019-09-24 20:18:00,422|13428|INFO|||log_trace.py|inner|47|||||||||结束执行test_get_trucks模块
